version: '3.9'

services:
  db:
    image: postgres:15
    container_name: transcriber-db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ..
      dockerfile: docker/bot.Dockerfile
    container_name: transcriber-bot
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../.env

  worker:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    container_name: transcriber-worker
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - "8081:8081"

volumes:
  postgres_data: